[package]
name = "rypper"
version = "0.1.0-alpha.4"
edition = "2021"
authors = [ "Soc Virnyl Estela <socvirnyl.estela@gmail.com>" ]
documentation = "https://uncomfyhalomacro.codeberg.page/rypper"
description = "An alternative package manager for openSUSE"
homepage = "https://codeberg.org/uncomfyhalomacro/rypper"
repository = "https://codeberg.org/uncomfyhalomacro/rypper"
license = "MPL-2.0"
keywords = [ "package-manager", "opensuse", "zypper", "rpm" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpm = "0.11.0"
rypper-cli = {   version = "0.1.0-alpha.4", path = "rypper-cli" }
rypper-core = {  version = "0.1.0-alpha.4", path = "rypper-core" }
rypper-utils = { version = "0.1.0-alpha.4", path = "rypper-utils" }

[workspace]
members = [
  "rypper-core",
  "rypper-cli",
  "rypper-utils",
  "rypper-reader"
]

[profile.release]
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = false       # Strip symbols from binary.

[profile.release-stripped]
inherits = "release"
strip = true
