#!/usr/bin/just

build: get-deps-book
	mdbook build
	echo "Docs built."
	echo "Entering book directory..."
	(cd book && \
	git init && \
	git config --global user.name "${CI_REPO_OWNER}" user.email "${MAIL}" && \
	git remote add origin "https://${RYPPER_ACCESS_TOKEN}@codeberg.org/${CI_REPO}.git" && \
	git switch --orphan pages && \
	git add -A && \
	git commit -m "update book for commit ${CI_COMMIT_SHA}" && \
	git push --force -u origin pages)

get-deps-book:
	zypper --non-interactive install mdbook git

