matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  build:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo
      - echo "Starting build"
      - cargo build --release --all-features
      - echo "Finished build"
  audit:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo cargo-audit
      - echo "Starting audit"
      - cargo audit
      - echo "Finished auditing"
  test:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo
      - echo "Starting tests"
      - cargo test --release --all-features
      - echo "Finished tests"

runs_on: [ success, failure ]
branches: [ main ]
