matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  build:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install just
      - just get-deps build

branches: 
  include: [ main, develop ]
  exclude: [ pages, docs, feature/* ]
runs_on: [ success, failure ]
