matrix:
  platform:
    - linux/amd64
    - linux/arm64
    - linux/386
    - linux/s390x
    - linux/ppc64le

platform: ${platform}

pipeline:
  build:
    when:
      event: [push, tag]
      branch: main
      status: [ success ]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo
      - echo "Starting build"
      - cargo build --release --all-features
      - echo "Finished build"
  audit:
    when:
      event: [push, tag]
      branch: main
      status: [ success ]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo
      - echo "Starting audit"
      - cargo audit
      - echo "Finished auditing"
  test:
    when:
      event: [push, tag]
      branch: main
      status: [ success ]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo
      - echo "Starting tests"
      - cargo test --release --all-features
      - echo "Finished tests"

