matrix:
  platform:
    - linux/amd64

platform: ${platform}

steps:
  docs:
    when:
      event: [push, tag]
      branch: 
        include: [ main, develop ]
    image: opensuse/tumbleweed:latest
    secrets: [ rypper_access_token, mail ]
    commands:
      - zypper --non-interactive install just
      - just docs

depends_on:
  - build
  - test

runs_on: [ success ]
