matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  build:
    when:
      event: [tag, deployment]
      branch: main
      status: [ success ]
    image: registry.opensuse.org/devel/bci/tumbleweed/containerfile/opensuse/389-ds:latest
    commands:
      - echo "Starting build"
      - cargo build --release --all-features
      - echo "Finished build"
      - cargo pubish --token "$CARGO_REGISTRY_TOKEN"
    secrets: [ cargo_registry_token ]

depends_on:
  - build

runs_on: [ success ]
