matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  publish:
    when:
      event: [tag, deployment]
      branch: 
        include: [ main, develop ]
    image: opensuse/tumbleweed:latest
    secrets: [ cargo_registry_token ]
    commands:
      - zypper --non-interactive install just
      - just publish

depends_on:
  - test
  - release
  - docs

runs_on: [ success, failure ]
