matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  build:
    when:
      event: [tag, deployment]
      branch: main
      status: [ success ]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper install -n cargo
      - echo "Starting build"
      - cargo build --release --all-features
      - echo "Finished build"
      - cargo pubish --token "$CARGO_REGISTRY_TOKEN"
    secrets: [ cargo_registry_token ]

depends_on:
  - build

runs_on: [ success ]
