matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  build:
    when:
      event: [tag, deployment]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install cargo
      - echo "Starting build"
      - cargo build --release --all-features
      - echo "Finished build"
      - cargo publish --token "$CARGO_REGISTRY_TOKEN"
    secrets: [ cargo_registry_token ]

depends_on:
  - build

branches: [ main ]
