matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  publish:
    when:
      event: [tag, deployment]
    image: opensuse/tumbleweed:latest
    secrets: [ cargo_registry_token ]
    commands:
      - zypper --non-interactive install just
      - just publish
branches: 
  include: [ main, develop ]
  exclude: [ pages, docs, feature/* ]
runs_on: [ success, failure ]
