matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  release:
    when:
      event: [push, tag]
      branch: 
        include: [ main, develop ]
        exclude: [ pages, docs, feature/* ]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install just
      - just get-deps build-release

depends_on:
  - test
  - docs

runs_on: [ success, failure ]
