matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  test:
    when:
      event: [push, tag, pull_request]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install just
      - just get-deps test
      - just test

depends_on:
  - build

runs_on: [ success, failure ]
