matrix:
  platform:
    - linux/amd64

platform: ${platform}

pipeline:
  build:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install just
      - just get-deps build-release
  docs:
    when:
      event: [push, tag]
    image: opensuse/tumbleweed:latest
    secrets: [ rypper_access_token, mail ]
    commands:
      - zypper --non-interactive install just
      - just docs
  publish:
    when:
      event: [tag, deployment]
    image: opensuse/tumbleweed:latest
    secrets: [ cargo_registry_token ]
    commands:
      - zypper --non-interactive install just
      - just publish

branches: 
  - include: [ main, develop ]
  - exclude: [ pages, docs, feature/* ]
runs_on: [ success, failure ]
